[package]
name = "kgrs"
description = "A library for Kagurin.rs"
version = "0.4.9"
edition = "2021"
authors = ["Rinrin.rs <rinrin0413.valley@gmail.com>"]
license = "[GPL-3.0] GNU General Public License v3.0"
repository = "https://github.com/Rinrin0413/kagurin-rs/kgrs/"

[dependencies]
rand = "0.8.5"
serde_json = "1.0.78"
thousands = "0.2.0"

[dependencies.serenity]
version = "0.10.10"
default-features = false
features = ["client", "gateway", "rustls_backend", "model", "cache", "unstable_discord_api"]

[dependencies.uuid]
version = "0.8.2"
features = ["v4"]

[dependencies.chrono]
version = "0.4.19"
default-features = false
features = ["clock"]

[dependencies.reqwest]
version = "0.11.11"
features = ["json"]

[dependencies.serde]
version = "1.0.137"
features = ["derive"]