[package]
name = "kgrs"
version = "0.2.0"
edition = "2021"
authors = ["Rinrin.rs rinrin0413.valley@gmail.com"]
license = "[GPL-3.0] GNU General Public License v3.0"
repository = "https://github.com/Rinrin0413/kagurin-rs/kgrs/"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = { version = "0.10.10", default-features = false, features = ["client", "gateway", "rustls_backend", "model"] }